// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYOMnDOBXZgBlup5Tw1twxWUXh8KXFu5A',
    appId: '1:226588533435:android:b6b349731c7480352e7f9e',
    messagingSenderId: '226588533435',
    projectId: 'esp-firebase-demo-a15c2',
    databaseURL: 'https://esp-firebase-demo-a15c2-default-rtdb.firebaseio.com',
    storageBucket: 'esp-firebase-demo-a15c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNU7RvbBnLGy7YO6DZAdissxttkIe_tq4',
    appId: '1:226588533435:ios:30030ed40b2fca832e7f9e',
    messagingSenderId: '226588533435',
    projectId: 'esp-firebase-demo-a15c2',
    databaseURL: 'https://esp-firebase-demo-a15c2-default-rtdb.firebaseio.com',
    storageBucket: 'esp-firebase-demo-a15c2.appspot.com',
    iosClientId: '226588533435-lt0cfc0bdsdjo1u6f79rn4mevtvsgk72.apps.googleusercontent.com',
    iosBundleId: 'com.slumberjer.sfarmskte',
  );
}
